---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: ubuntu2004
    template_name: ubuntu-20-04
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: prepare.yml
    destroy: ../default/destroy.yml
    converge: ../default-install/converge.yml
    verify: ../default-install/verify.yml
verifier:
  name: ansible
