- name: Apt update
  ansible.builtin.shell: apt-get update

- name: Apt install ca-certificates,...
  ansible.builtin.shell: apt-get install -y ca-certificates curl gnupg

- name: Apt install docker
  ansible.builtin.shell: apt-get install -y docker

- name: Install docker compose
  ansible.builtin.shell: curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose

