---
roles:
  - src: "git+https://github.com/FabOS-AI/molecule_vsphere.git"
    scm: git
    version: develop
    name: molecule_vsphere

  - src: "git+https://github.com/FabOS-AI/molecule_openstack"
    scm: git
    version: main
    name: molecule_openstack