---
roles:
  - name: ipa-big.molecule_openstack
    version: 1.0.10

  - src: "git+https://github.com/eclipse-slm/slm-ansible-role-python"
    scm: git
    version: main
    name: slm-ansible-role-python
