---
dependency:
  name: galaxy
driver:
#  name: default
  name: delegated
platforms:
  - name: ubuntu2004-zss
    template_name: ubuntu-20-04
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    prepare: prepare.yml
    destroy: ../default/destroy.yml
    converge: ../default-install/converge.yml
    verify: verify.yml
verifier:
  name: ansible
