---
# tasks file for docker
- name: Prepare target host for docker installation
  ansible.builtin.include_tasks: prepare.yml
  when: state == "prepare"

- name: Install docker on target host
  ansible.builtin.include_tasks: install.yml
  when: state == "present"

- name: Uninstall docker on target host
  ansible.builtin.include_tasks: uninstall.yml
  when: state == "absent"
