---
- name: Get Python Version
  block:
    - name: Get Python version (python3)
      ansible.builtin.raw: python3 --version
      register: python_version_raw
      failed_when: false
      changed_when: false

    - name: Get Python version (python)
      when: '"command not found" in python_version_raw.stdout'
      ansible.builtin.raw: python --version
      register: python_version_raw
      failed_when: false
      changed_when: false

    - name: Store detected Python version text
      ansible.builtin.set_fact:
        python_version_text: "{{ (python_version_raw.stdout | default('') | trim) or (python_version_raw.stderr | default('') | trim) }}"

    - name: Store detected Python version
      ansible.builtin.set_fact:
        python_version: "{{ (python_version_text | regex_search('([0-9]+\\.[0-9]+\\.[0-9]+)', '\\1')) | default('unknown') }}"

    - ansible.builtin.debug:
        msg: "Detected Python version: {{ python_version }}"

- name: Get Distribution ID
  block:
    - name: Detect distribution id
      ansible.builtin.raw: . /etc/os-release && echo ${ID:-unknown}
      register: distro_id
      failed_when: false
      changed_when: false

    - name: Debug distribution id
      ansible.builtin.debug:
        var: distro_id.stdout | default('') | trim

- name: Prepare (Debian)
  when: distro_id.stdout | default('') | trim == 'debian'
  block:
    - name: Get Debian version id
      ansible.builtin.raw: . /etc/os-release && echo ${VERSION_ID:-unknown}
      register: debian_version_id_raw
      failed_when: false
      changed_when: false

    - name: Store Ubuntu major version
      ansible.builtin.set_fact:
        debian_major_version: "{{ (debian_version_id_raw.stdout | default('') | trim | regex_search('^([0-9]+)', '\\1'))[0] | default('unknown') }}"

    - ansible.builtin.debug:
        msg: "Detected Debian major version: {{ debian_major_version }}"

    - name: Prepare Debian 11
      when: debian_major_version == '11'
      ansible.builtin.include_tasks: dist-specific/debian11_prepare.yml

- name: Update Python (Ubuntu)
  when: distro_id.stdout | default('') | trim == 'ubuntu'
  block:
    - name: Get Ubuntu version id
      ansible.builtin.raw: . /etc/os-release && echo ${VERSION_ID:-unknown}
      register: ubuntu_version_id_raw
      failed_when: false
      changed_when: false

    - name: Store Ubuntu major version
      ansible.builtin.set_fact:
        ubuntu_major_version: "{{ (ubuntu_version_id_raw.stdout | default('') | trim | regex_search('^([0-9]+)', '\\1'))[0] | default('unknown') }}"

    - ansible.builtin.debug:
        msg: "Detected Ubuntu major version: {{ ubuntu_major_version }}"

    - name: Update Python (Ubuntu 18)
      when: ubuntu_major_version == '18'
      ansible.builtin.include_tasks: dist-specific/ubuntu_18_prepare.yml

    - name: Update Python (Ubuntu 20)
      when: ubuntu_major_version == '20'
      ansible.builtin.include_tasks: dist-specific/ubuntu_20_prepare.yml

- name: Update Python (CentOS)
  when: distro_id.stdout | default('') | trim == 'centos'
  block:
    - name: Get CentOS version id
      ansible.builtin.raw: . /etc/os-release && echo ${VERSION_ID:-unknown}
      register: centos_version_id_raw
      failed_when: false
      changed_when: false

    - name: Store Ubuntu major version
      ansible.builtin.set_fact:
        centos_major_version: "{{ (centos_version_id_raw.stdout | default('') | trim | regex_search('^([0-9]+)', '\\1'))[0] | default('unknown') }}"

    - debug:
        msg: "Detected CentOS major version: {{ centos_major_version }}"

    - name: Update Python (CentOS 7)
      when: centos_major_version == '7'
      ansible.builtin.include_tasks: dist-specific/centos_7_prepare.yml

    - name: Update Python (CentOS 8)
      when: centos_major_version == '8'
      ansible.builtin.include_tasks: dist-specific/centos_8_prepare.yml


