- name: Apt update
  ansible.builtin.shell: apt-get update

- name: Apt install
  ansible.builtin.shell: apt-get install -y ca-certificates curl gnupg

- name: Install keyring
  ansible.builtin.shell: install -m 0755 -d /etc/apt/keyrings

- name: Get docker gpg keyring
  ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

- name: Chmod keyring
  ansible.builtin.shell: chmod a+r /etc/apt/keyrings/docker.gpg

- name: Add repo to apt sources
  ansible.builtin.shell: |
    echo \
      "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Apt update
  ansible.builtin.shell: apt-get update

- name: Apt install
  ansible.builtin.shell: apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

- name: Install docker compose
  ansible.builtin.shell: curl -SL https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose

