---
- name: Converge - Install (ssh)
  hosts: ssh
  gather_facts: yes
  become: yes
  tasks:
    - name: "Include docker - state = present"
      ansible.builtin.include_role:
        name: "docker"

- name: Converge - Install (winrm/win-ssh)
  hosts: winrm:win-ssh
  gather_facts: no
  become: yes
  tasks:
    - name: Gathering Facts
      ansible.windows.setup:
        gather_subset:
          - "!all"
      async: 30
      poll: 5
      retries: 3

    - name: "Include docker - state = present"
      ansible.builtin.include_role:
        name: "docker"