---
- name: Add stable docker repository
  ansible.builtin.command: |
    yum-config-manager --add-repo https://download.docker.com/linux/centos/{{ ansible_facts['distribution_major_version'] }}/x86_64/stable
  changed_when: false
  failed_when: false

- name: Install docker
  ansible.builtin.shell: |
    yum update -y && yum install -y docker-ce docker-ce-cli containerd.io --nogpgcheck
  changed_when: false

- name: Enable and Start docker daemon
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: true

- name: Install 'PyYAML' pip package (CentOS 7)
  ansible.builtin.command: /usr/local/bin/python3.11 -m pip install PyYAML==6.0.3 requests==2.33.1
  changed_when: false