---
- name: Replace mirror for bullseye-backports lines in sources.list
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: 'http://deb.debian.org/debian bullseye-backports'
    replace: 'http://archive.debian.org/debian bullseye-backports'

- command: cat /etc/apt/sources.list
  register: sources_list_content
  changed_when: false

- debug:
    var: sources_list_content.stdout_lines
