- name: Set desired python version
  ansible.builtin.set_fact:
    python_version: "3.9"

- name: Add deadsnakes repo and install python
  ansible.builtin.raw: |
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y software-properties-common
    add-apt-repository -y ppa:deadsnakes/ppa
    apt-get update
    apt-get install -y python{{ python_version }} python{{ python_version }}-venv \
      python{{ python_version }}-distutils python3-pip
  changed_when: false

- name: Set Interpreter
  ansible.builtin.set_fact:
    ansible_python_interpreter: "/usr/bin/python{{ python_version }}"