---
- name: Install supportive packages via apt (version > 20)
  when: ansible_facts["distribution_major_version"] | int > 20
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - gnupg
      - python3-pip
    update_cache: yes
  register: apt_result
  retries: 20
  delay: 10
  until: apt_result.rc is not defined
  become: yes

- name: Install supportive packages via apt (version <= 20)
  when: ansible_facts["distribution_major_version"] | int <= 20
  ansible.builtin.shell: apt-get update && apt-get install -y ca-certificates gnupg
  register: apt_result
  changed_when: false

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  register: apt_key_result
  until: not apt_key_result.failed
  retries: 20

- name: Set up the stable repository (version > 20)
  when: ansible_facts["distribution_major_version"] | int > 20
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present

- name: Set up the stable repository (version <= 20)
  when: ansible_facts["distribution_major_version"] | int <= 20
  ansible.builtin.shell: |
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  changed_when: false

- name: Install docker engine (version > 20)
  when: ansible_facts["distribution_major_version"] | int > 20
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
  register: apt_result
  until: apt_result.rc is not defined
  retries: 20
  delay: 10

- name: Install docker engine (version <= 20)
  when: ansible_facts["distribution_major_version"] | int <= 20
  ansible.builtin.shell: apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io
  changed_when: false

- name: Install pip packages (Ubuntu >= 24)
  when: (ansible_facts["distribution_major_version"] | int >= 24)
  ansible.builtin.apt:
    pkg:
      - python3-docker
  register: apt_pip_result
  until: not apt_pip_result.failed
  retries: 20

- name: Install pip packages (Ubuntu == 22)
  when: ansible_facts["distribution_major_version"] | int == 22
  ansible.builtin.pip:
    name:
      - PyYAML==6.0.3
  register: pip_result
  until: not pip_result.failed
  retries: 20

- name: Install pip packages (Ubuntu <= 20)
  when: ansible_facts["distribution_major_version"] | int <= 20
  ansible.builtin.command: /usr/local/bin/pip3.12 install PyYAML==6.0.3 requests==2.33.1
  changed_when: false
