---
# defaults file for docker
state: present
expose_docker_tcp_port_default: false
expose_tcp_port:
  files:
    - src: daemon.json
      dest_dir: /etc/docker/
      dest_file: daemon.json
    - src: override.conf
      dest_dir: /etc/systemd/system/docker.service.d/
      dest_file: override.conf

## Windows
reboot_delay_default: 240

docker_desktop_download_url: https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe
docker_desktop_download_dest_folder: C:\Users\ansible\Downloads\
docker_desktop_download_dest_file: Docker-Desktop-Installer.exe
docker_desktop_download_dest_full_path: "{{docker_desktop_download_dest_folder}}{{docker_desktop_download_dest_file}}"
docker_desktop_binary_folder: "C:\\Program Files\\Docker\\Docker"
docker_desktop_binary: "Docker Desktop.exe"

docker_desktop_product_id: "Docker Desktop" # For more information see: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_package_module.html#parameter-provider
docker_desktop_service_name: "Docker Desktop Service"
docker_desktop_windows_features:
  - Microsoft-Windows-Subsystem-Linux
  - Microsoft-Hyper-V
  - Containers
docker_desktop_windows_daemon_config_path: "C:\\Users\\{{ ansible_user }}\\.docker"
docker_desktop_windows_daemon_config_file: "windows-daemon.json"
docker_desktop_windows_daemon_config_full_path: "{{ docker_desktop_windows_daemon_config_path }}\\{{ docker_desktop_windows_daemon_config_file }}"
docker_desktop_firewall_rule_name: Docker Daemon TCP Port