---
dependency:
  name: galaxy
driver:
  name: default
platforms:
  #  CENTOS:
  - name: centos7
    image_name: CentOS 7 64-bit
    groups: ['ssh']
provisioner:
  name: ansible
  playbooks:
    create: ../default/create-os.yml
    prepare: ../default-install/converge.yml
    destroy: ../default/destroy-os.yml
    converge: ../default-uninstall/converge.yml
    verify: ../default-uninstall/verify.yml
verifier:
  name: ansible
