---
- name: Check firewalld status (CentOS)
  when: ansible_distribution == 'CentOS'
  ansible.builtin.service_facts:

- name: Add firewall rule (CentOS)
  when:
    - ansible_distribution == 'CentOS'
    - ansible_facts.services['firewalld.service'] is defined
    - ansible_facts.services['firewalld.service'].state == "running"
  block:
    - name: Install python-firewall (CentOS7/9)
      when: ansible_distribution_major_version != "8"
      ansible.builtin.yum:
        name: python-firewall

    - name: Install firewall python package (CentOS8)
      when: ansible_distribution_major_version == "8"
      ansible.builtin.yum:
        name: python3-firewall

    - name: Add firewall rule for port 2375
      ansible.posix.firewalld:
        zone: public
        port: 2375/tcp
        permanent: true
        state: enabled
      register: firewalld_output

    - name: Reload Firewalld
      when:
        - firewalld_output.changed
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded


- name: Make sure directories of config files are created
  ansible.builtin.file:
    path: "{{ item.dest_dir }}"
    state: directory
  loop: "{{ expose_tcp_port.files }}"

- name: Copy config files to remote
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest_dir }}{{ item.dest_file }}"
  loop: "{{ expose_tcp_port.files }}"
  register: copy_action_results

- name: Reload + Restart docker daemon
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  when: copy_action_results.changed