---
- name: Remove docker-compose binary (not CentOS8)
  when: (ansible_distribution != 'CentOS') or (ansible_distribution_major_version != "8")
  block:
    - name: Pip freeze docker-compose
      ansible.builtin.shell: pip freeze | grep docker-compose
      changed_when: false
      failed_when: false
      register: pip_freeze_dc

    - name: Remove docker compose binary (when not pip package)
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        state: absent
      when: '"docker-compose" not in pip_freeze_dc.stdout'
      register: remove_docker_compose

- name: Remove docker-compose binary (CentOS8)
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == "8"
  block:
    - name: Pip3 freeze docker-compose
      ansible.builtin.shell: pip3 freeze | grep docker-compose
      changed_when: false
      failed_when: false
      register: pip_freeze_dc

    - name: Remove docker compose binary (when not pip package)
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        state: absent
      when: '"docker-compose" not in pip_freeze_dc.stdout'
      register: remove_docker_compose


- name: Remove old conflicting packages
  ansible.builtin.apt:
    pkg:
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
      - containerd
      - runc
    state: absent
  when: (ansible_distribution == 'Ubuntu')