---
- name: Add stable docker repository (CentOS 8)
  when: ansible_facts["distribution_major_version"] == "8"
  ansible.builtin.command: |
    yum config-manager --add-repo https://download.docker.com/linux/centos/{{ ansible_facts['distribution_major_version'] }}/x86_64/stable
  changed_when: false

- name: Add stable docker repository (CentOS >= 9)
  when: ansible_facts["distribution_major_version"] | int >= 9
  ansible.builtin.yum_repository:
    name: docker
    description: Docker stable repository
    baseurl: "https://download.docker.com/linux/centos/{{ ansible_facts['distribution_major_version'] }}/x86_64/stable"
    gpgcheck: false

- name: Install docker (CentOS 8)
  when: ansible_facts["distribution_major_version"] == "8"
  ansible.builtin.shell: |
    yum update -y && yum install -y docker-ce docker-ce-cli containerd.io --nogpgcheck
  changed_when: false

- name: Install docker (CentOS >= 9)
  when: ansible_facts["distribution_major_version"] | int >= 9
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: true

- name: Enable and Start docker daemon
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: true

- name: Install pip3 (CentOS >= 9)
  when: ansible_facts["distribution_major_version"] | int >= 9
  ansible.builtin.yum:
    name: python3-pip

- name: Upgrade pip
  ansible.builtin.pip:
    name: pip
    state: latest

- name: Remove python3-requests rpm-package (CentOS >= 9)
  when: ansible_facts["distribution_major_version"] | int >= 9
  ansible.builtin.package:
    name:
      - python3-requests
      - python3-PyYAML
    state: absent

- name: Install pip packages (Centos <= 9)
  when: ansible_facts["distribution_major_version"] | int <= 9
  ansible.builtin.pip:
    name:
      - PyYAML==6.0.3
      - requests==2.32.5
  ignore_errors: true

- name: Install pip packages (Centos > 9)
  when: ansible_facts["distribution_major_version"] | int > 9
  ansible.builtin.pip:
    name:
      - PyYAML==6.0.3
      - requests==2.33.1
  ignore_errors: true