- name: Get Status of Docker Engine Service
  ansible.windows.win_service:
    name: docker
  register: docker_service_state

- name: Unregister Docker Engine Service
  ansible.windows.win_command: '"C:\Program Files\Docker\Docker\resources\dockerd.exe" --unregister-service'
  when: docker_service_state.exists
  register: unregister_docker_service_cmd
  changed_when: unregister_docker_service_cmd.rc == 0
  failed_when:
    - unregister_docker_service_cmd.rc == 1
    - "not 'zum Löschen markiert' in unregister_docker_service_cmd.stdout"

- name: Uninstall docker-desktop
  ansible.windows.win_package:
    path: "{{ docker_desktop_download_url }}"
    arguments: uninstall --quiet
    product_id: "{{ docker_desktop_product_id }}"
    state: absent
  timeout: 300
  retries: 5